version: "3"
services:
  web:
    build: ./docker/php
    container_name: back
    ports:
      - "8000:80"
    env_file: ./.env
    depends_on:
      - mysql
    networks:
      - back
    environment:
      - DATABASE_URL=mysql://${DATABASE_USER}:${DATABASE_PASSWORD}@${DATABASE_HOST}:3306/${DATABASE_NAME}
    volumes:
      - ./back:/var/www/html

  mysql:
    image: mariadb:10
    container_name: mysql
    volumes:
      - ./db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - "3306:3306"
    networks:
      - back

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    depends_on:
      - mysql
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=mysql
    networks:
      - back
volumes:
  db_data:
networks:
  back: {}
